[workspace]
members = ["codegen"]

[package]
name = "monads-rs"
version = "0.1.0"
edition = "2021"

[dependencies.monads-rs-codegen]
version = "0.1.0"
path = "codegen"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "option_benchmark"
harness = false
